src/bin/zmcontrol

- fix: [CO-183] service-discover status in the status
provide service discover running status in status
- fix: skip service-discover while start
prevent reporting error for service-discover service
while starting services.[being a systemd service]

fix: [CO-183] service-discover status and logging

---

src/libexec/zmfixperms

these folders are required by HSM features.
I'm following same old logic, as soon as systemd user-owning mechanisms will be finally in place (hope ASAP)

chore: create empty cache and incoming folders

---

src/libexec/zmproxyconfgen

update the executable path for ProxyConfGen util according to the new changes made in https://github.com/Zextras/carbonio-mailbox/pull/45

chore: [CO-298] update ProxyConfGen executable path

---

src/bin/zmcontrol

* Add new command (`-V` that prints out `carbonio*` packages installed on the machine and its version)
Tested locally

fix(CO-309): zmcontrol -v shows all info now

---

src/bin/zmmailboxdctl

We found that mailbox process is unable to read carbonio-mailbox token file, despite zextras user being in carbonio-mailbox group. On further analysis we discovered that the process runs with "root" supplementary group, because zmmailboxdmgr is started as sudo and it runs jetty with root inherited groups.
- **zmmailboxdmgr now runs as zextras user**
It was checked with "ps" command that supplementary groups are not "root' anymore, instead they are the one zextras user belongs to (e.g.: carbonio-mailbox)
**Before applying this change we should stop the mailbox process, as zmmailboxdctl won't be able to stop it after changes are applied due to dropped priviliges.**

feat(zmmailboxdctl): run zmmailboxdmgr as zextras with correct groups

---

src/libexec/zmdailyreport

zmdailyreport is still needed and with it also pflogsumm and perl-date-calc
carbonio-pflogsumm is now a direct dependency of carbonio-mta (without passing for carbonio-logger now-defunct meta-package)
check also
https://github.com/Zextras/carbonio-build/pull/41

chore: IN-545: re-add zmdailyreport

---

src/bin/jetty
src/bin/ldap
src/bin/ldap.production
src/bin/zmamavisdctl
src/bin/zmcbpolicydctl
src/bin/zmclamdctl
src/bin/zmconfigdctl
src/bin/zmfreshclamctl
src/bin/zmmemcachedctl
src/bin/zmopendkimctl

This is meaningful in itself but also toward the not-so-distant systemd units. Having a `kill -9` has undesiderated effects on systemd evaluated EXIT_STATUS, resulting in an implict exit(1) on services stop.
Tested on both zmcontrol and systemd powered environments.

chore: avoid kill -9 to gracefully kill the processes

---

src/bin/zmantivirusctl
src/bin/zmcontrol

**What has changed:**
- do not control and report amavisd status if component is missing in case of single server clamav setup
- correctly report antivirus running for clamav only setups
- prevent parameter expansion eveywhere
see CO-597 for context.

feat: [CO-656] make zmantivirusctl handle also clamav only setup

---

src/libexec/certbot

Now will actually trigger certonly command if dry-run was successful.
Related PR: https://github.com/Zextras/carbonio-mailbox/pull/175

feat: [CO-621] Add certbot certonly execution

---

src/libexec/zmfixperms

This also sports some old z references removal and general shell linting pass

chore: zmfixperms: apply proper privileges for nginx logs

---

src/libexec/zmfixperms

early in the first steps of zmfixperm there's a `chown -R root:root /opt/zextras/common` that breaks carbonio-certbot and carbonio-core privileges checks.
At the end of carbonio-core postinst there a zmfixperms, so let's add another check on it, with the hope to deprecate the zmfixperms logic early

fix: [IN-590] apply proper privileges for certbot folder

---

src/bin/carbonio

Hi, 
as a step of the splitting project, we completed the issue related to the deployment of `carbon-advanced-cli` as a separate jar from `carbon-advanced`. This means that the entry point of the `carbonio` can directly execute the cli main with only it's own dependencies loaded in the `classpath`.

feat: [COR-913] deploy Carbonio Advanced CLI as indipendent jar

---

src/libexec/zmdbintegrityreport

**What has changed:**
- `zmdbintegrityreport` now performs required cleans-up in the mysql datadir before performing checks and optimization on databases.  
- removal of empty directories is the only cleanup added to avoid potential `mysqlcheck` check failures.

fix: [COR-820] Perform 'datadir' cleanup before running checks

---

src/bin/zmproxyctl

Capability for nginx to bind on privileged ports is provided by this line
https://github.com/zextras/carbonio-core-utils/blob/main/src/libexec/zmfixperms#L619

fix: nginx: don't use sudo but leverage the CAP_NET_BIND_SERVICE=+ep

---

conf/zmlogrotate

This will work both on ubuntu and rhel.
On ubuntu, although there's a /run/syslog.pid, they are using rsyslog and syslog.service is an rsyslog.service alias.

fix: logrotate doesn't restart (r)syslog on rhel

---

src/libexec/zmfixperms

This fix a chmod error with emty argument for filepaths (happens on mta-proxy nodes)

fix: zmfixperms: allow chmod on empty db/data

---

conf/zmconfigd.cf
src/bin/zmjava
src/bin/zmjavaext
src/bin/zmlocalconfig
src/bin/zmmailboxdctl
src/bin/zmplayredo
src/bin/zmpython
src/libexec/zmfixperms
src/libexec/zmjsprecompile

- point to new mailbox jars location in /opt/zextras/mailbox/jars
- zmmailboxdctl use zmmailboxdmgr. Java options are evaluated in binary file /usr/bin/carbonio-appserver (see: https://github.com/zextras/carbonio-mailbox/pull/490)

refactor: [CO-1046] embedded jetty

---

src/libexec/ldapmoduleconfupdate

This script will run during the post-installation hook of the **carbonio-directory-server** package upon upgrades. 
Its purpose is to **ensure that the LDAP module configuration is updated whenever modifications are applied to the modules loaded by carbonio-openldap**.
The decision to include this script here, rather than directly in the carbonio-directory-server package, is based on historical reasons. Additionally, separating this script helps prevent code duplication across different distribution-specific post-installation instructions in the PKGBUILD file.
**Linked PRs:**
- https://github.com/zextras/carbonio-mailbox/pull/548
- https://github.com/zextras/carbonio-core/pull/75

feat: [CO-1343] Add LDAP module config update script

---

src/bin/carbonio

Once we merge:
https://github.com/zextras/carbonio-advanced-cli/pull/80
it should be possible to run carbonio-advanced-cli using only `/usr/share/carbonio-advanced-cli/*` as classpath

fix: use only carbonio-advanced-cli classpath to run the cli

---

src/bin/trainsa.sh

@M0Rf30 Through a typo introduced in 366ca364ea33e03b4382b727ebfb0ed68e597831 temporary directories for the SA training operation are created with a trailing `-d` in the name, while the script attempts to remove temporary directories without it at the end of the operation.
Result: temporary directories survive each operation.

fix: trainsa.sh: missing space prevents removal of temporary directories

---

conf/configd.cf

web.xml has been removed from carbonio-appserver.
This causes some warnings in zmconfigd:
`File "/opt/zextras/common/lib/jylibs/state.py", line 758, in rewriteConfig     for line in open(fr).readlines():`
`zmconfigd[7367]: Rewrite failed: [Errno 2] No such file or directory: '/opt/zextras/conf/web.xml.in' ([Errno 2] No such file or directory: '/opt/zextras/conf/web.xml.in')`

refactor: [CO-1767] remove web.xml and mailbox restart on change
